### ISSUE TITLE
[UI] 초기 세팅

### ISSUE THREAD

**Issue by Zzu-h** [Zzu-h/AfreecaTV#9]
### 📌 내용
초기 세팅

### 🛠 ToDo
- [x] Main Activity 위에 Home Fragment / Detail Fragment를 띄운다.
- [x] style 세팅
- [x] icon 및 이미지 세팅
- [x] color 세팅
- [x] Jetpack Navigation 세팅

**Comment by Zzu-h** [comment]
icon - people / mores
image - afreecaTV / 팬 / ???
